#!/bin/sh

# Set default start/boot
#-----------------------

logger -p local6.notice -t installer "app-openvpn-core - enabling OpenVPN server"
chkconfig openvpn on

logger -p local6.notice -t installer "app-openvpn-core - starting OpenVPN server"
service openvpn start
