#!/bin/sh

# Set default start/boot
#-----------------------

if [ -e /etc/pki/CA/sys-0-cert.pem ]; then
    logger -p local6.notice -t installer "app-openvpn-core - enabling OpenVPN server"
    chkconfig openvpn on

    logger -p local6.notice -t installer "app-openvpn-core - starting OpenVPN server"
    service openvpn start
fi

# Initialize domain name with default
#------------------------------------

/usr/clearos/apps/openvpn/deploy/initialize

# Reload clearsyncd
#------------------

/sbin/service clearsyncd condrestart >/dev/null 2>&1
