<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['openvpn_app_description'] = 'Aplikacja OpenVPN umożliwia bezpieczny, zdalny dostęp do tego systemu oraz sieci lokalnej.';
$lang['openvpn_app_name'] = 'OpenVPN';
$lang['openvpn_auto_configure_help'] = 'Serwer OpenVPN aktualnie znajduje się w trybie auto konfiguracji.  Jeżeli zmienisz ustawienia sieciowe, OpenVPN inteligentnie naniesie zmiany w swojej konfiguracji.  Jeżeli chciałbyś wyłączyć tryb auto konfiguracji, proszę kliknąć na poniższy przycisk.';
$lang['openvpn_internet_hostname_tooltip'] = 'The Internet Hostname is used in the OpenVPN client configuration provided to end users.  This hostname can be changed in the IP Settings app.';
$lang['openvpn_linux'] = 'Linux';
$lang['openvpn_mac_os'] = 'MacOS';
$lang['openvpn_windows'] = 'Windows';
